In [1]:
# Numpy -fundamental libraires for scientific calculation in python.
# -> provide support for array and metrices along with collc. of mathematical functions to operate on these data structures.


In [2]:
! pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 330.3 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.9 kB 393.8 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 464.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.3 MB 3.2 MB/s eta 0:00:06
    --------------------------------------- 0.3/16.3 MB 3.2 MB/s eta 0:00:06
   - -------------------------------------- 0.6/16.3 MB 4.8 MB/s eta 0:00:04
   -- ------------------------------------- 1.2/16.3 MB 6.9 MB/s eta 0:00:03
   ---- ----------------------------------- 1.8/16.3 MB 7.7 MB/s eta 0:00:02
   ----- ---------------------------------- 2.4/16.3 MB 8.9 MB/s eta 0:00:02
   ------- -------------------------------- 3.0/16.3 MB 9.1 MB/s eta 0:00:02
   -------- ------------------------------- 3.6/16.3 MB 9.5 MB/s eta 0:00:02
  


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
#create 1d array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)

[1 2 3 4 5]
(5,)


In [8]:
# 2 d array
arr2=np.array([[2,4,5],[3,40,89]])
print(arr2)
print(arr2.shape)

[[ 2  4  5]
 [ 3 40 89]]
(2, 3)


In [13]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [17]:
#Matrix with all values as 1
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#vectorized operations.
a1=np.array([1,2,3,4,5])
a2=np.array([10,20,30,40,50])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [24]:
arr=np.array([11,22,33,44,55])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[3.31662479 4.69041576 5.74456265 6.63324958 7.41619849]
[5.98741417e+04 3.58491285e+09 2.14643580e+14 1.28516001e+19
 7.69478527e+23]
[-0.99999021 -0.00885131  0.99991186  0.01770193 -0.99975517]
[2.39789527 3.09104245 3.49650756 3.78418963 4.00733319]


In [26]:
# slicing and indexing...
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
print(arr[1:,2:])
print(arr[0:2,2:])

[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [30]:
#Modify the array element
arr[0,0]=10
arr

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
#statics concept of numpy--- i.e. called normalisation
# normalisation: it means that having a mean of 0 and standard deviation of 1.
data=np.array([1,2,3,4,5])

mean=np.mean(data)
std_deviation=np.std(data)
#Normalising the data
normalized_data=(data-mean)/std_deviation
normalized_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [34]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
#mean
mean=np.mean(data)
print(mean)
#median
median=np.median(data)
print(median)
#standard deviation
std_dev=np.std(data)
print(std_dev)

#variance
variance=np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25


In [36]:
#Logical Operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5)&(data<=8)]

array([5, 6, 7, 8])